kind: Service
apiVersion: v1
metadata:
  name: sca-hazelcast-headless
  namespace: mprj-marco-carvalho-dev
  labels:
    app: sca-hazelcast-openshift-mvp
spec:
  clusterIP: None
  publishNotReadyAddresses: true  
  ports:
    - name: hazelcast
      protocol: TCP
      port: 5701
      targetPort: 5701
  selector:
    app: sca-hazelcast-openshift-mvp
      
