apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sca-hazelcast-openshift-mvp
  labels:
    app: sca-hazelcast-openshift-mvp
spec:
  to:
    kind: Service
    name: sca-api-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect